#!/usr/bin/env perl
use 5.010;
use Getopt::Std;
use Algorithm::Permute;
use Term::ANSIColor qw(:constants);

getopts('v');

$v = $opt_v ? "-v" : "";
while(<>)
{
	chomp ;
	next if ($_ eq "");
	say "./push_swap $_ | ./checker $v $_";
	$out = `./push_swap $_ | ./checker $v $_`;
	say $out if ($opt_v);
	die "KO\n" if ($out eq "KO");
	$argnbr = split(/\s/);
	$res = `./push_swap $_ | wc -l | bc`;
#	die "KO\n" if ($argnbr <= 3 && $res > 3);
#	die "KO\n" if ($argnbr <= 5 && $res > 8);
	print GREEN "OK\n", RESET;
}
