#!/usr/bin/env perl
use 5.010;
use Getopt::Std;
use Algorithm::Permute;
use Term::ANSIColor qw(:constants);

getopts('veor');

$max = 0;
while(<>)
{
	chomp ;
	next if ($_ eq "");
	say "./push_swap $_ | ./checker -v $_" if ($opt_e);
	$out = `./push_swap $_ | ./checker $_`;
	system "./push_swap $_ | ./checker -v $_" if ($opt_v);
	die "KO\n" if (not $out eq "OK\n");
	$argnbr = split(/\s/);
	$res = `./push_swap $_ | wc -l | bc`;
	say "oprations: $res" if ($opt_o);
	$max = $res if ($res > $max);
	print GREEN "OK\n", RESET if ($opt_r);
}
print "max $max";
