#!/usr/bin/env perl
use 5.010;
use Getopt::Std;
use Algorithm::Permute;
use Term::ANSIColor qw(:constants);

getopts('vp');

if ($opt_p)
{
	system "rm cases";
	$i = 2;
	while ($i < 5)
	{
		my @array = 1..$i;
		my $p_iterator = Algorithm::Permute->new ( \@array );
		while (my @perm = $p_iterator->next) {
			system "echo @perm >> cases";
		}
		$i = $i + 1;
		system "echo >> cases";
	}
	exit(0);
}

$v = $opt_v ? "-v" : "";
while(<>)
{
	chomp ;
	next if ($_ eq "");
	$out = `../push_swap $_ | ../checker $v $_`;
	say $out if ($opt_v);
	die "KO" if ($out eq "KO");
	$argnbr = split(/\s/);
	$res = `../push_swap $_ | wc -l | bc`;
	die "KO" if ($argnbr <= 3 && $res > 3);
	die "KO" if ($argnbr <= 5 && $res > 8);
	print GREEN "OK ", RESET;
}
